wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.10
    start_time: 1677593809.217495
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.9.10
      5: 0.13.10
      8:
      - 2
      - 5
